# Generated by Django 3.2.3 on 2021-06-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='taxation_id_id',
        ),
    ]
