# Generated by Django 3.2.3 on 2021-06-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_transaction_id_order_taxation_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxation_id_id',
            new_name='taxation_id',
        ),
    ]
