# Generated by Django 3.2.3 on 2021-06-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_taxation_id_id_order_taxation_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxation_id',
            new_name='transaction_id',
        ),
    ]
